name: json_locale_generator
description: A generation tool that builds a class to get your json locale paths from dart code
version: 0.1.0
homepage: https://github.com/ronw98/json_locale_generator
repository: https://github.com/ronw98/json_locale_generator
issue_tracker: https://github.com/ronw98/json_locale_generator/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: '^2.0.0'
  build: '>=2.0.0 <3.0.0'
  build_config: '>=1.0.0 <2.0.0'
  collection: ^1.15.0
  glob: ^2.0.0
  path: '>=0.9.0 <2.0.0'
  recase: '>=4.0.0 <5.0.0'
  yaml: ^3.1.0


dev_dependencies:
  build_test: ^2.0.0
  lint: ^1.0.0
  test: any
