name: example
description: A new Flutter application.
version: "1.0.0"
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  json_locale:
    path: ../

dev_dependencies:
  json_locale_generator:
    path: ../../json_locale_generator
  build_runner: ^2.4.5

json_to_dart:
  sample_files:
    - source: assets/en.json
      class_name: Locale
      plural_matcher: "-[0-9]+$"